server:
  port: 8080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kt3_omos?useUnicode=true&characterEncoding=utf-8
    username: kt3
    password: kt3
  application:
    name: Account Service
